# Basic Site Settings
locale: "ko-KR"
site_theme: "contrast"
title: "Luna_Blog"
title_separator: "-"
name: &name "Luna"
description: &description "보안 공부 내용을 기록하는 공간입니다."
url: "https://1120luna.github.io"
baseurl: "" 
repository: "1120luna/1120luna.github.io"

# Site Author
author:
  avatar: "profile.png"
  name: "Luna"
  bio: "Security"
  location: "South Korea"
  employer: "University Student"
  github: "1120luna"

# Site Settings
breadcrumbs: true
words_per_minute: 160
future: true
read_more: "disabled"
atom_feed:
  hide: true  # FEED 아이콘 제거

# Conversion & Plugins
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: Asia/Seoul

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
